### ISSUE TITLE
identify LengthAndFilesizeDoNotMatch error message

### ISSUE THREAD

**Issue by forensenellanebbia** [brimorlabs/rdpieces#1]
I used "bmc-tools.py -b" to extract all the BMP files from "Test-Cache-Files/Cache/Cache0000.bin", but I get a long list of errors when I run _rdpieces.pl_ script no matter the OS/ImageMagick version I use:

C:\Tools>perl rdpieces.pl -s test_source -output test_dest

_Operating System is listed as MSWin32
Found the Windows slashes

Imagemagick is installed on this system. Continuing with script

***** Created directory test_dest under the path C:\Tools\test_dest
***** Created directory C:\Tools\test_dest\Data\ under the path C:\Tools\test_dest\Data\
***** Created directory C:\Tools\test_dest\Rebuilt\ under the path C:\Tools\test_dest\Rebuilt\

***** Processing C:\Tools\test_source\Cache0000.bin_0000.bmp
identify: LengthAndFilesizeDoNotMatch `C:\Tools\test_source\Cache0000.bin_0000.bmp' @ error/bmp.c/ReadBMPImage/845.
***** NOTICE: Histogram contains only 1 color(s), moving to next file

***** Processing C:\Tools\test_source\Cache0000.bin_0001.bmp
identify: LengthAndFilesizeDoNotMatch `C:\Tools\test_source\Cache0000.bin_0001.bmp' @ error/bmp.c/ReadBMPImage/845.
***** NOTICE: Histogram contains only 1 color(s), moving to next file

***** Processing C:\Tools\test_source\Cache0000.bin_0002.bmp
identify: LengthAndFilesizeDoNotMatch `C:\Tools\test_source\Cache0000.bin_0002.bmp' @ error/bmp.c/ReadBMPImage/845.
magick: LengthAndFilesizeDoNotMatch `C:\Tools\test_source\Cache0000.bin_0002.bmp' @ error/bmp.c/ReadBMPImage/845.
identify: UnableToOpenBlob 'C:\Tools\test_dest\Data\Cache0000.bin_0002-T.bmp': No such file or directory @ error/blob.c/
OpenBlob/3537._

and the parsing never completes.

All the Perl modules are installed (these are the ones shown on Win7):
- cpan install IO::All - IO::All is up to date (0.87).
- cpan install Getopt::Long - Getopt::Long is up to date (2.51).
- cpan install DBI - DBI is up to date (1.643).
- cpan install File::Copy - File::Copy is up to date (2.34).

These are the software combinations I've tried so far with no luck:
- Windows 7 SP1 x86 /strawberry-perl-5.30.2.1-32bit/ImageMagick-7.0.10-24-portable-Q8-x86
- Ubuntu 18.04 x64/Perl v5.26.1/ImageMagick 7.0.10-24 Q16 x86_64 2020-07-27
- Windows 10 1809 x64/strawberry perl 5.30.2.1 64bit/ImageMagick-7.0.10-24-Q8-x64-dll or ImageMagick-7.0.10-24-Q16-HDRI-x64-dll

Do I have to use a specific version of ImageMagick?

Thanks

**Comment by brimorlabs** [comment]
Hi there! Thanks for the notice, and thanks so much for actually including details, it makes trying to figure out whats wrong so much easier, compared to "it doesn't work" 😄 

It looks like ImageMagick is failing opening the files, I believe I had it called to run with no warnings, because in the verbose mode it (IM) gave errors of the length/file size not matching. I will dig into it and see if I can figure out exactly why it is failing, its probably just a flag or something that changed in one of the newer releases, but have to figure out "why" its happening when I have some time to dig into it!

**Comment by brimorlabs** [comment]
@forensenellanebbia 

I finally got around to figuring out why this was happening, it was because the ANSSI script header is off by four bytes. I opened a bug request for them, but in the meantime I added the modified version of the bmc-tools script to the rdpieces repository, that has the proper mathiness. I hope that it helps!

Brian

**Comment by forensenellanebbia** [comment]
I just tried your modified version and it's working great. Thanks!
